### ISSUE TITLE
Newly installed plugin doesn't appear in Adminimize settings

### ISSUE THREAD

**Issue by jpgklassen** [bueltge/adminimize#102]
#### Version Information
* WordPress: 4.9.6
* Multisite: false
* Adminimize: 1.11.4

#### Steps to Reproduce
1. Install and activate Adminimize
2. Install and activate Invisible reCaptcha for WordPress
3. Go to Settings > Adminimize and look for Invisible reCaptcha. It is not there.

#### What I Expected
I expected to be able to hide Invisible reCaptcha in the Settings menu for certain roles using Adminimize.

#### What Happened Instead
There was no option to hide Invisible reCaptcha in the Settings menu for certain roles using Adminimize.

#### Screenshot or Video
![adminimize-screenshot](https://user-images.githubusercontent.com/10780140/41392163-d738c64a-6f53-11e8-913b-41fe1a87dcda.png)

**Comment by bueltge** [comment]
Please update the settings of Adminimize again and check, maybe now it is inside the settings. The plugin read, write the settings on each update process.

**Comment by bueltge** [comment]
No, normally if you switch to the settings page; maybe this was an error for the current installation.
