### ISSUE TITLE
WPBakery menu page items 

### ISSUE THREAD

**Issue by mnimri** [bueltge/adminimize#103]
Hi, I have WPBakery installed and I am having trouble hiding these two submenu items. I see the issue documented here:

https://wordpress.org/support/topic/cant-hide-wpbakery-page-builder/

But there is no resolution. Have you found a fix for this?

<img width="318" alt="screen shot 2018-07-02 at 6 49 19 pm" src="https://user-images.githubusercontent.com/39780720/42191478-b367e794-7e28-11e8-9b10-73f4f34226b0.png">

**Comment by bueltge** [comment]
Sorry, not really. I think it was a part for custom options to add the menu item, that have in the non-admin roles an different slug. If you  send me an access as admin and user role that you will hide, I can check this and add this as hint in this issue.

**Comment by pwkip** [comment]
It wasn't too intuitive, but I managed to fix it like this:
1. Go to settings > Adminimize
2. Expand Menu Options and scroll all the way down until you see "Your Own Options slug"
3. Enter `vc-welcome` in the left box, and also enter `vc-welcome` in the right box
4. Click "Update options"
5. Expand the Menu Options again and scroll down to the same place. You will see, that at the end of the list a new option is added called "vc-welcome Custom"
6. Check the box under teh desired user role
7. Click"Update Options"

![image](https://user-images.githubusercontent.com/1150196/65605481-72342d80-dfa9-11e9-87a4-11c074d95aef.png)

**Comment by bueltge** [comment]
Thanks again for helping! 
The topic is also inside the Wiki - https://github.com/bueltge/adminimize/wiki
