### ISSUE TITLE
Need To Create Slug To Block Plugin Menu On Plugin Dashbaord

### ISSUE THREAD

**Issue by chapsmurf** [bueltge/adminimize#104]
#### Version Information
* WordPress: 4.9.6
* Multisite: false
* Adminimize:  1.11.4

I am trying to block sub-menus created within the Newsletter plugin. I can easily block the menu items in the Admin menu, but I cannot seem to block them within the plugin. 

The URL's look like this:

https://<mydoamin.com>/wp-admin/admin.php?page=newsletter_users_massive
https://<mydoamin.com>/wp-admin/admin.php?page=newsletter_users_export

How can these be blocked please? I have attached a screenshot of the plugin menu so you can see what I am referring to. 

![newsletter_sub_menu](https://user-images.githubusercontent.com/40858011/42381418-e4f478c4-8128-11e8-9c58-7488dae652df.JPG)

**Comment by bueltge** [comment]
The plugin can't remove areas in dependency of the slug, url.

But you can hide areas with a css selector. IN your context try to remove menu items from the "subscribers" menu via css. Use the global options area, add a custom item like

left textarea: `Newsletter Menu Subscribeers4item`
right textarea: `#tnp-header > ul > li > ul > li:nth-child(4)`

The new settings remove the 4th menu item in this list, in this example the export menu item,

![image](https://user-images.githubusercontent.com/133425/42511198-79597552-8451-11e8-9887-e4c4ae270e93.png)

**Comment by chapsmurf** [comment]
Hi Frank,

That's pretty cool. Many thanks for looking in to this and providing me with an answer. Can I ask, how did you determine what the CSS child name was (in your example you gave `nth-child(4)`)? 

I have added up to number 7 ('nth-child(1), nth-child(2), nth-child(3)' etc), and then all of a sudden the entire menu was removed, bar one menu (List Building>WP Users Integration). This is actually perfectly fine, because now with almost that entire menu gone, I can control access from the via Adminimize using the normal menu items. 

Once again, thank you for coming up with this solution. I really appreciate it.

**Comment by bueltge** [comment]
The solution is to know how it works css selectors. 
A small hint to this post: https://css-tricks.com/how-css-selectors-work/

Adminimize hide all areas in this context, but don't check capabilities. I mean if you have users with knowledge about this technic they have the chance to find access to this areas.
