### ISSUE TITLE
Plugin may not hide meta boxes when user has multiple roles

### ISSUE THREAD

**Issue by filipecsweb** [bueltge/adminimize#105]
#### Version Information
* WordPress: 4.9.7
* Multisite: false
* Adminimize: 1.11.4

#### Steps to Reproduce
1. Make sure you have User Role Editor activated so you can set multiple roles for a user;
2. Login with a user who is an administrator;
3. Go to Users > All Users and grant the current user the roles Author and Contributor;
4. Go to Settings > Adminimize;
5. In "Write options - Post" deactivate Title for Author;
6. Open a new tab, go to Posts > Add New, see that the Title box wasn't hidden;
7. Go back to "Write options - Post" and deactivate Title for Contributor. It doesn't matter whether you uncheck Title for Author or not;
8. Now see that the Title box is hidden.

I'm sending a pull request soon. The changes I've done in the code are all well explained.

I'd really appreciate if you merged it with master and updated the plugin in the WP repository asap. Thanks!

**Comment by bueltge** [comment]
Thanks a lot for your hint, contribution. The PR is now also inside the master branch, maybe you will checkout and test?

**Comment by filipecsweb** [comment]
Thanks for merging.

I just tested your master branch and is working fine.

**Comment by filipecsweb** [comment]
Bad news...

Just realized I fixed it just for the post type 'post' and not to work with metaboxes within custom post types.

Anyway, I've already changed the code to work with CPTs. Do you think it's better to open other issue and send another pull request?

**Comment by filipecsweb** [comment]
Just figured it out, look at the new PR.

**Comment by bueltge** [comment]
Thanks again for your help. Please read my comments to close and merge this PR. :heart:

**Comment by bueltge** [comment]
The PR is merged, ready for testing. Maybe we can close this issue and I will rollout in the next version on w.org.

**Comment by filipecsweb** [comment]
Thanks!

I just tested your master and it's working fine. I'll leave the issue for you to close. The help I gave you is nothing compared to what you've done to help me.

**Comment by bueltge** [comment]
Thanks a lot! Nice praise. :heart:
