### ISSUE TITLE
create_function() deprecated in PHP 7.2

### ISSUE THREAD

**Issue by bunglegrind** [bueltge/adminimize#109]
In

adminimize\inc-setup\remove-admin-bar.php line 240

Cheers

**Comment by bueltge** [comment]
Thanks for the hint. I will switch to http://uk.php.net/functions.anonymous because I don't support smaller 5.6 inside the plugin, although I know we have users there use php 5.2.

**Comment by bueltge** [comment]
HI @bunglegrind 
maybe you can test the master branch in this context?

**Comment by bunglegrind** [comment]
Tested with PHP 7.2, 7.0, 5.6.

I tried to access to /wp-admin/edit.php when admin bar in global options is disabled. 
No more PHP warning, it works!

Thanks.

**Comment by bueltge** [comment]
Wow, thanks for this fast test and reply!

**Comment by bunglegrind** [comment]
Many thanks for your plugin!
