### ISSUE TITLE
Elementor Edit option doesn't hide from Front End Admin Bar

### ISSUE THREAD

**Issue by latinlifestyle** [bueltge/adminimize#111]
#### Version Information
* WordPress: 4.9.8
* Multisite: false
* Adminimize: 1.11.4

Hi there

I'm trying to hide the Edit Elementor option from a Front End Admin Bar on a post, but is not working for neither Editor or Admin. Unfortunately Front End Admin Bar section doesn't allow you to add a custom ID or Class. Any help? By the way there is a info at the bottom saying "You must open the front end of the site in this browser in order for the plugin to discover the Admin Bar items that are currently not visible." but I have no clue what that mean...I tried everything...

HELP PLEASE

**Comment by latinlifestyle** [comment]
It worked. I had some caching issue.
Thanks.

**Comment by bueltge** [comment]
Also as hint, inside the [Wiki](https://github.com/bueltge/adminimize/wiki) you should fine solutions for 3th party plugins, like Elementor.
