### ISSUE TITLE
Imported adminize.json causes plugin to break.

### ISSUE THREAD

**Issue by flameoftheforest** [bueltge/adminimize#116]
#### Version Information
* WordPress: 5.0.3
* Multisite: false
* Adminimize: 1.11.4

#### Expression of Thanks
First and foremost, thank you so much for this plugin! It is very useful. You guys deserve all the good things in life because you have really make my life as a software janitor a lot easier.

#### Steps to Reproduce
1. Export settings to JSON file
2. Import settings
3. Error thrown: `"Cannot use object of type stdClass as array in /var/www/html/wp-content/plugins/adminimize/inc-options/menu_options.php:191"`

#### What I Expected
Plugin Settngs Page renders normally.

#### What Happened Instead
Plugin Settings Page stops rendering after Menu-Options > Settings > Discussions.

#### What I did to fix it:
+ This is caused by `$wp_submenu[ "options-general.php" ]` having a `$submenuItem` of "object" type.
+ This is however, **NOT** the  root-cause because:
    + It happens only after I import adminize configuration from the JSON file.
+ in `menu_options.php`, in above line 191 the following check:
```
if (is_object($subitem)) {
    $subitem = json_decode(json_encode($subitem), true);
}
```
+ This is not the best solution:
   + It address only the symptoms not the cause
   + There's a cost of an extra check and convert.

Please consider the fix and/or look into how to address the cause of this issue.

Thank you!
Bryan 
Hillsong.com

**Comment by bueltge** [comment]
Should be fixed with the last commit ^ and released in the new version 1.11.8
