### ISSUE TITLE
Feedback after testing version 1.11.5-dev

### ISSUE THREAD

**Issue by byzdata** [bueltge/adminimize#120]
#### Version Information
* WordPress: 5.1
* PHP: 7.0.33
* Apache: 2.4
* MariaDB: 10.2
* Multisite: false
* Adminimize: 1.11.5-dev

#### Comments
I have used the plugin to hide some admin content for an specific user role, which was created after installing the plugin Sportpress (https://wordpress.org/plugins/sportspress/). The user role is defined as "League Manager".
Using Adminimize, I was able to check the desired checkbox under the column role "League Manager"
The enviroment and screens did not freeze. The checkboxes remained checked after move among menus, and even after log out/in.
I was able to hide some elements (after checked them using the Inspector), under the own custom options, either using an ID (starting with a pound sign '#') or using a Class (starting with a dot '.')
I have attached the .json file with all the setting I have checked. (I think it might help you to understand what I have done)

From my experience the plugin runs pretty well.

[mw_adminimize-settings-export-06-21-2019.txt](https://github.com/bueltge/adminimize/files/3316220/mw_adminimize-settings-export-06-21-2019.txt)

**Comment by bueltge** [comment]
Thanks a lot for helpful feedback and time. The new version is now live. Best
