### ISSUE TITLE
Multisite Super Admin

### ISSUE THREAD

**Issue by reportcode** [bueltge/adminimize#121]
Backend Options -> Exclude Super Admin

When this option is enabled it ought to also:

a) prevent everyone except Super Admin from accessing or editing Adminimize Options

b) apply the Adminimize Options made by Super Admin to all Subsites

**Comment by bueltge** [comment]
This option check only for this right, so if you are Super Admin do you have no reducing of areas inside the back end. The options are checked via the capability 'manage_options'. If users have this option they have still access to the options page of Adminimize.
