### ISSUE TITLE
New Menu not appearing in configuration section

### ISSUE THREAD

**Issue by eceramanan** [bueltge/adminimize#125]
#### Version Information
* WordPress: 4.9.6
* Multisite: false
* Adminimize: 1.11.5

#### Steps to Reproduce
1. Installed Adminimize plugin, configured menu for each role. Everything was working as expected.
2. Installed new Plugin for different purpose. It is displayed as New Menu in Left side admin menu
3. Now I want to control this new menu for each role. Navigated to Adminimize settings page. 
4. Menu is not appearing under "Menu options - Menu, Submenu" section

#### What I Expected
1. I was expecting the new menu under "Menu options - Menu, Submenu" section of Adminimize settings page

#### What Happened Instead
1. new menu item is missing under "Menu options - Menu, Submenu" section of Adminimize settings page

**Comment by bueltge** [comment]
Please try to update the settings from Adminimize so that the plugin will rewrite all menu items and other stuff from the back-end. I trigger this rewrite only on eachsave to save storage and speed.

**Comment by eceramanan** [comment]
@bueltge thanks for your response. I tried Updating the Adminimize settings, Un install and re installed the plugin but did not work for me. Finally I deleted saved plugin details, after which it was resolved. I re configured everything :(

**Comment by bueltge** [comment]
Was you also as Administrator on other pages, there are the menu items is visible? After new installation is the menu item visible inside the settings page? However you have also the possibility to export, import the settings.

**Comment by eceramanan** [comment]
- Yes I am Administrator. I was able to see the menu item on left had side menu. 
- In Adminimize settings page menu was not available for configure.
- Regarding Export and import, I tried it. Exported the settings, then cleared the plugin related data. Then I was able to see the new menu item available for configuration. Now I tried importing into the system and found the new menu item missing for configuration.

**Comment by bueltge** [comment]
>In Adminimize settings page menu was not available for configure.
You mean the area inside the settings or the whole settings page?

**Comment by eceramanan** [comment]
New Menu item was not appearing under "Menu options - Menu, Submenu" section inside settings page of Adminimize plugin

**Comment by bueltge** [comment]
So, hard to save without access to the area. But for now is solved of you has reinstall the plugin. So we should close the issue.

**Comment by eceramanan** [comment]
For now I am done. Will try with different site and will update you next time. By the way thanks for the plug-in. It was very handy for role based access management.

**Comment by bueltge** [comment]
Fine, please add any update about the topic.
