### ISSUE TITLE
does not work with "Admin Menu Editor" 

### ISSUE THREAD

**Issue by bueltge** [bueltge/Adminimize#13]
http://wordpress.org/support/topic/does-not-work-with-admin-menu-editor
http://wordpress.org/support/topic/conflict-with-admin-menu-editor-plugin-2

Check Adminimize with http://wordpress.org/plugins/admin-menu-editor/

**Comment by nczz** [comment]
Hi @bueltge ,

Seems 1.11.3 version does not work with "Admin Menu Editor" again after upgrade from 1.11.2.

My Env.
WordPress 4.8.3 / PHP7 / Nginx 1.10

PS: Downgrade to 1.11.2 works fine! (thank you)

**Comment by bueltge** [comment]
Hi @nczz 
please can you try the current master branch, development version. I have changes different thinks in this context. Download: https://github.com/bueltge/Adminimize/archive/master.zip
Thanks for testing and Feedback.

**Comment by nczz** [comment]
Hi @bueltge ,

It works great after test! wow~ thank you for so that quick reply!

Wait your upgrade notification from WordPress!

Thank you again. It's really a nice plugin.

**Comment by bueltge** [comment]
Thanks a lot for your fast feedback!
