### ISSUE TITLE
Advanced CF7 DB always hide

### ISSUE THREAD

**Issue by brandingaddicted** [bueltge/adminimize#132]
#### Version Information
* WordPress: 5.4
* Multisite: false
* Adminimize: 1.11.6

#### Steps to Reproduce
1. Settings > Adminimize > Menu Options
2. Advanced CF7 DB (Group) unchecked
3. Advanced CF7 DB (Slug: contact-form-listing) unchecked
4. Import CSV (Slug: import_cf7_csv) unchecked
5. Developer Support unchecked
6. Add-ons unchecked

#### What I Expected
Plugin would be visibile on backend for the user role called "staff"

#### What Happened Instead
Plugin is always hide for user "staff"

#### Screenshot or Video
<img width="1298" alt="Schermata 2020-04-10 alle 13 54 46" src="https://user-images.githubusercontent.com/63452984/78989107-ee035b00-7b32-11ea-9c05-7608c9160b09.png">

<img width="1440" alt="Schermata 2020-04-10 alle 13 56 55" src="https://user-images.githubusercontent.com/63452984/78989172-27d46180-7b33-11ea-9387-447383741fb1.png">

**Comment by bueltge** [comment]
This plugin can only hide areas, not change the user capabilities to visible areas there are not allowed from the plugin author of other plugins, like CF7. CF7 hide these areas for your role Staff and Adminimize can't help you to solve them.
