### ISSUE TITLE
Menu Options Do Not Deactivate

### ISSUE THREAD

**Issue by dteadmin2020** [bueltge/adminimize#134]
Menu Options Do Not Deactivate when I'm trying to hide certain items under the role "Order Manager".

I've recently updated Woocommerce and Wordpress and the issue started occurring.  Versions below.

I've checked the slugs from a suggestion from another thread, and they are fine e.g. Reports i.e. wc-reports.

Has Adminimize checked compatibility up to WC and WP versions as per below?

The item I need to hide is Woocommerce > Reports menu option.  I was told I need to allow "View Woocommerce Reports" in User Role Editor, then use Adminimize to deactivate just the Reports menu item. 

Please help asap as I would prefer hiding this sensitive financial information from users.

#### Version Information
WordPress:  5.3.1
Woocoommerce: 4.1.0
Multisite: true/false     FALSE
Adminimize:   1.11.6

#### Screenshot or Video

![image](https://user-images.githubusercontent.com/65213956/81891553-0e1fb180-95ec-11ea-9021-e37bb3bf8885.png)

**Comment by bueltge** [comment]
same like #130 
Should fix in the next version.
