### ISSUE TITLE
Noticing redirect to 404 upon adminimize save

### ISSUE THREAD

**Issue by crystalgroves** [bueltge/adminimize#137]
When I try to save adminimize I get redirect to 404 and the options don't seem to save. Doesn't happen every time, but does happen when I try to do mass edits for menu items.

#### Version Information
* WordPress: 5.4.2
* Multisite: false
* Adminimize: 1.11.6
Running php 7.1

#### Steps to Reproduce
1. Go to Adminimize as admin
2. Select menu options
3. Mass select for subscribers to eliminate ability to go into backend

#### What I Expected
It would save

#### What Happened Instead
It goes to 404

#### Screenshot or Video
https://www.loom.com/share/6c071ac7072a444f9f2096f618802469

**Comment by bueltge** [comment]
Hello @crystalgroves 
please deactivate all other plugins and use a default theme. Try again. I mean a other code, like from a plugin or form the Theme will change the redirect after save the options. Please get feedback after this step. 
Have you tried to save only one item inside the settings? Maybe the server has a problem with too much values inside the send data process.
