### ISSUE TITLE
no settings saving- after I tick and save the setting to hide no ticks remain and nothing is saved. please help!

### ISSUE THREAD

**Issue by jennanorthwood** [bueltge/adminimize#142]
#### Version Information
* WordPress: 
* Multisite: true/false
* Adminimize: 

#### Steps to Reproduce
1. 
2. 
3.

**Comment by bueltge** [comment]
No redirect after saving the options?
Look at the URL inside the browser, do you get a change?
Have you [read this](https://wordpress.org/support/topic/menu-options-values-lost-upon-upgrade/#post-7147440), linked from the Wiki on this Repository?

**Comment by jennanorthwood** [comment]
Thanks for your reply. It does redirect and says that it has "been saved" but it actually hasnt?

**Comment by jennanorthwood** [comment]
Thanks for the article link.... but I dont understand it sorry. Im not a coder. Is there a simple way for me to fix it or will i need a coder to do that?

**Comment by jennanorthwood** [comment]
Hi Frank, I have read that and tried my best but no luck. Any other tips for me? I have uninstalled and reinstalled and all sorts - thank you

**Comment by bueltge** [comment]
Please describe the workflow, the result,maybe a short video or screenshot that help me to understand. Please try it without other plugin and a default theme.
