### ISSUE TITLE
Admin bar front end options missing 

### ISSUE THREAD

**Issue by zawayavision** [bueltge/adminimize#145]
#### Version Information
* WordPress: 5.7.1
* Multisite: false
* Adminimize: 1.11.7

Hello, 
First tank you for this plugin it's really great one 
At "Admin bar front end options" the cheek case are missing, i try to disable all the others plugin but it's not work, also uninstall and install Adminize plugin but also not resolve

![Screenshot_1](https://user-images.githubusercontent.com/82902857/115480951-155b3080-a23b-11eb-899b-406e26fde084.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/82902857/115480979-1f7d2f00-a23b-11eb-92e4-a3eb73da9bf5.jpg)

**Comment by bueltge** [comment]
You must switch to the front-end of your site, logged in as Administrator, and then back to the settings page of Adminimize. Because the plugin reads with your user rights the data and create the settings area.
