### ISSUE TITLE
PHP 8 Fatal Error

### ISSUE THREAD

**Issue by fintinc** [bueltge/adminimize#148]
#### Version Information
* WordPress:  5.7.2
* Multisite:  false
* Adminimize: 1.11.7

#### Steps to Reproduce
1. Activate: Global options > Admin Color Scheme
2. Go To Profile

#### What happens 
`PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, int given in  wp-admin/user-edit.php:297`

**Comment by bueltge** [comment]
Hello @fintinc 
Please verify them, especially your installed version of the plugin. Replace all files and remove old one if you do not use the automatic updates from the WP instance. Because the option to the color scheme for user is removed since version 1.10.0
