### ISSUE TITLE
[Bug]: not updated in two years

### ISSUE THREAD

**Issue by shaktimanpurush** [bueltge/adminimize#151]
### Description of the bug

The plugin has not been updated in two years, and has several issues and security risks.
You can read in the wordpress repository a long list of issues.

### Reproduction instructions

You can see in WP plugins that it is abandoned, all the users are left in the cold.

### Expected behavior

PLEASE update it.
Why not start a crowdfunding on your Wordpress Plugin page ? LOTS of people would contribute and donate money, so that your great plugin can continue.

THANK YOU

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bueltge** [comment]
There are no security issues on the list, only bugs from several third-party topics. The question for help from others is older than the last update, also on the plugin page as sticky - no response. So I do not see any helping hands here, no PR on GitHub, and no helping hands on the support forum. Why should I prioritize the topics and reduce my private time?

**Comment by shaktimanpurush** [comment]
hi, I understand your situation completely !
If you add a "donate post" on top of the Wordpress Support section, tons of people will donate !
How much donation would be suitable for you to devote some of your free time to updating this plugin ? I will check with my company how much we can spare to update this great plugin.
Best regards

**Comment by bueltge** [comment]
There is a donate button on the plugin page, also on the settings page of the plugin and at the GitHub page. I get one donation in the last year. So there is no financial interest to pay for maintenance or support.

**Comment by bueltge** [comment]
Update is life, but without improvements, only topics there are fixed on this GH repo.
