### ISSUE TITLE
[Bug]: Fatal error in '/inc-options/admin_bar_frontend.php' when options are imported

### ISSUE THREAD

**Issue by ControlZetaDigital** [bueltge/adminimize#155]
### Description of the bug

Hi

When you import a JSON file with options exported from another website, even if the websites are exactly the same, the plugin throws a **fatal error on line 87** of the file **'/inc-options/admin_bar_frontend.php'**.

I have detected the problem here:
Line 81: `foreach ( $admin_bar_frontend_items as $key => $value ) {`

I don't know why it happens, but when you import a json file with options, the variable `$value` is no longer an object, but an array.

I've solve the problem adding this line of code just after the foreach line:
`$value = (is_object($value)) ? $value : (object) $value;`

If this is a common bug, I hope this can help to solve it.

Cheers

### Reproduction instructions

1. Go to Import / Export options
2. Import a JSON file previously exported
3. Update the changes and the fatal error will be thrown

### Expected behavior

Don't get a fatal error when importing options

### Environment info

- Adminimize 1.11.8
- Wordpress 6.0.3
- PHP 8.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bueltge** [comment]
Thanks for the note. Why not send a PR for this bug?

**Comment by ControlZetaDigital** [comment]
Hi all, sorry I've just read your response @bueltge

@borsodigerii thanks for sending PR of the fix that I suggested, I was about to send it right now but you were faster

**Comment by bueltge** [comment]
Thanks a lot for the feedback and the PR. The new version should be public in view minutes on wp.org.
