### ISSUE TITLE
Tab for each settings area?

### ISSUE THREAD

**Issue by bueltge** [bueltge/adminimize#17]
One thing that IMHO is a bit problematic it the length of settings page. Maybe it would be a good idea to use separate tab for each section?

**Comment by ajitbohra** [comment]
Having tabs for each would definitely improve the usability

**Comment by bueltge** [comment]
@ajitbohra Maybe you can help on the development?

**Comment by ajitbohra** [comment]
@RalfAlbert currently planning out how we can effectively implement this will soon share more details

**Comment by bueltge** [comment]
No, @RalfAlbert is currently in other jobs, have not enough time to develop on the plugin. I search for more helping hands, maybe you. The branch v2.0 is the idea, start for a new version. The master is the current version, only for bugfixing. But the code is bad and the developing is hard. That's was the point for a re-factoring in branch v2.0.

**Comment by ajitbohra** [comment]
oops by mistake mentioned ralfalbert i mean to say working on tabs will soon update how we can approach that. We will have it on separate branch. Have been using plugin from past several months but never felt need to look into code, currently going through the code to understand.

**Comment by bueltge** [comment]
It's would be great, if you can help.

**Comment by ajitbohra** [comment]
Count me in :)

**Comment by bueltge** [comment]
Can you send pull requests, that I can see, how is the quality. It is fine, then I will add your user to this repository.

**Comment by ajitbohra** [comment]
Sure as soon as something is ready will send the pull request so that you can review

**Comment by bueltge** [comment]
:+1:

**Comment by bueltge** [comment]
Implemented since #112
