### ISSUE TITLE
Would it be possible to make the menu disabling valid for page disabling too

### ISSUE THREAD

**Issue by bueltge** [bueltge/Adminimize#21]
when you disable a menu item it disables the capability too, thats would fine and helpful.

Maybe helpful: http://plugins.svn.wordpress.org/admin-menu-editor/

**Comment by SylviaDD** [comment]
Hi
how hidden the composer visual plugin tab., deactivate all options but the coming good item is semre visible. Podefixar this error?

Another issue is the toolbar at the front end, I can not access settings To send to refrech page but Noa aperece in it ...
help?

**Comment by bueltge** [comment]
Which tab do you mean, on which page? A Screenshot is really helpful and often easy to understand. 

Your admin bar topic is not clear for me. Can you explain what is your goal, what you do. It is a single install or a multisite installation. 

Thanks.

**Comment by SylviaDD** [comment]
Hi 

I'm trying to configure your plugin, as the images.

 

I want to hide some options in the menu bar at the fornt end of the site, the plugin asks you to select and to refrechs but leaves no access to the settings options.

 

can help.

 

as the composer visual plugin, I selected all of the options to hide, but always appears in the menu as in the picture attached.

How do I hide it completely (visual composer) using the plugin Adminimize?

 

Thanks

 

 

 

 

 

De: Frank Bültge [mailto:notifications@github.com] 
Enviada: quarta-feira, 27 de Janeiro de 2016 19:17
Para: bueltge/Adminimize
Cc: SylviaDD
Assunto: Re: [Adminimize] Would it be possible to make the menu disabling valid for page disabling too (#21)

 

Which tab do you mean, on which page? A Screenshot is really helpful and often easy to understand. 

Your admin bar topic is not clear for me. Can you explain what is your goal, what you do. It is a single install or a multisite installation. 

Thanks.

**Comment by bueltge** [comment]
Hi @SylviaDD  
the images are missing, can you add this to the issue, directly on the issue in github, not via mail. Maybe the mail functionality cut the images.

**Comment by SylviaDD** [comment]
Hi 

Thnks for your replay.

In the images i have a personal linfo. You dont have another e-mail for i send the images?

thnaks

 

De: Frank Bültge [mailto:notifications@github.com] 
Enviada: sexta-feira, 29 de Janeiro de 2016 11:58
Para: bueltge/Adminimize
Cc: SylviaDD
Assunto: Re: [Adminimize] Would it be possible to make the menu disabling valid for page disabling too (#21)

 

Hi @SylviaDD <https://github.com/SylviaDD> 

the images are missing, can you add this to the issue, directly on the issue in github, not via mail. Maybe the mail functionality cut the images.

**Comment by bueltge** [comment]
@SylviaDD yes, send to directly to me `frankATbueltgeDOTde`

**Comment by bueltge** [comment]
@SylviaDD yes, send to directly to me `frankATbueltgeDOTde`

But as hint, I have build a new workflow to hide menu items. Plugin, like Visual Composer, change the strings in the menu item and now I filter for a additional key. Please download this version (https://github.com/bueltge/Adminimize/archive/master.zip) here and test with this again. In my tests works the hiding of the Visual Composer really fine.

**Comment by SylviaDD** [comment]
Hi Frank 

Tanks for your help

I instaled a master zip and give me this error:


Fatal error: Cannot redeclare _mw_adminimize_get_plugin_data() (previously declared in /home/dinamica/public_html/loja-woodlacol.pt/wp-content/plugins/adminimize/adminimize.php:36) in /home/dinamica/public_html/loja-woodlacol.pt/wp-content/plugins/Adminimize-master/adminimize.php on line 44

 

 

You can help me?

Your e-mail is frankATbueltgeDOTde@ <mailto:frankATbueltgeDOTde@github.com> github.com ?

 

Thanks.

Silvia

 

De: Frank Bültge [mailto:notifications@github.com] 
Enviada: sexta-feira, 29 de Janeiro de 2016 14:23
Para: bueltge/Adminimize
Cc: SylviaDD
Assunto: Re: [Adminimize] Would it be possible to make the menu disabling valid for page disabling too (#21)

 

@SylviaDD <https://github.com/SylviaDD>  yes, send to directly to me frankATbueltgeDOTde

But as hint, I have build a new workflow to hide menu items. Plugin, like Visual Composer, change the strings in the menu item and now I filter for a additional key. Please download this version (https://github.com/bueltge/Adminimize/archive/master.zip) here and test with this again. In my tests works the hiding of the Visual Composer really fine.

**Comment by bueltge** [comment]
You can copy all files via ftp in the same plugin folder adminimize, now you have two different folder with the same plugin. 
Remove the folder adminimize-master and copy all files from the folder, withour the folder adminimize-master in you adminimize  directory.

**Comment by SylviaDD** [comment]
Hi Frank.

I remove the folder and now it’s ok. The plugin Works well and Hide the visual composer.

Thanks very mutch  for your quick help.

Silvia 

 

De: Frank Bültge [mailto:notifications@github.com] 
Enviada: sexta-feira, 29 de Janeiro de 2016 21:03
Para: bueltge/Adminimize
Cc: SylviaDD
Assunto: Re: [Adminimize] Would it be possible to make the menu disabling valid for page disabling too (#21)

 

You can copy all files via ftp in the same plugin folder adminimize, now you have two different folder with the same plugin. 
Remove the folder adminimize-master and copy all files from the folder, withour the folder adminimize-master in you adminimize directory.

**Comment by SylviaDD** [comment]
HI Frank
Have 2 items that can not hide.
https://nimbus.everhelper.me/client/notes/share/408848/wwx2yy8mqiiz7r2iluv1 
your plugin hides all other but as those two that are advertising plugin VISUAl composer does not hide 
how can I  do?

you can update please?
I've tried other sites and remains always the same.

Thanks

**Comment by bueltge** [comment]
Can you send me a zip of the plugin, that I can retest and check, how the plugin implement the menu items? Or give it a free version of the plugin?

**Comment by SylviaDD** [comment]
I want to hide everything from VC, you mail for send you a Zip free version of the plugin

**Comment by SylviaDD** [comment]
?

**Comment by bueltge** [comment]
Please send to frank AT bueltge DOT de
Thx.

**Comment by SylviaDD** [comment]
(https://github.com/bueltge/Adminimize/archive/master.zip)

**Comment by SylviaDD** [comment]
thanks ;)

**Comment by bueltge** [comment]
Hi Sylvia.
Why you add the master branch as zip? I need the Visual Composer plugin for testing in my environment?

**Comment by SylviaDD** [comment]
Hi. Sendme your mail, I send you a plugin VC

**Comment by bueltge** [comment]
Hi Sylvia,
currently I can find a mail from you with a attachment, the plugin?
Please can you check this, send the plugin again to me - `frank AT bueltge DOT de`

**Comment by SylviaDD** [comment]
'frank@bueltge.de' I send you. You recive?

**Comment by SylviaDD** [comment]
Is very big... I use the https://www.wetransfer.com you recive?

**Comment by bueltge** [comment]
Hi @SylviaDD 
Thanks, is here and tested.
But it works really fine on my tests.

Screenshot 1, the settings page of Adminimize and I hide it as example for the first role, Administrator.
![auswahl_001](https://cloud.githubusercontent.com/assets/133425/13487440/38de704a-e11a-11e5-969d-2fd7894cc485.jpg)

After switch to another page, the menu items is hide.
![auswahl_002](https://cloud.githubusercontent.com/assets/133425/13487447/456f17f6-e11a-11e5-8fa8-36b220848c6a.jpg)

**Comment by SylviaDD** [comment]
Hi thanks .But I need it for the users, is possible for editor and colaborador?

**Comment by SylviaDD** [comment]
For the editor apears the welcome Visual Composer like the image https://nimbus.everhelper.me/client/notes/share/408848/wwx2yy8mqiiz7r2iluv1

**Comment by bueltge** [comment]
You can hide it for all roles, but you can not change the capability that user have access to the plugin. For this goal use the plugin Members and change the capability of the roles.

**Comment by SylviaDD** [comment]
Hi Frank. OK.
thank you very much for your help! well there.
Where can I buy this plugin

**Comment by SylviaDD** [comment]
admin.php?page=vc-welcome 
I can Hide this, Where I clik for hid these page?

You can send me the css for hide? How mutch it cost?

**Comment by SylviaDD** [comment]
think it makes no sense, ocultares the tab for the visible administrator and letting for utilizadores..instalei the plugin members but does not work ...
is that you can not apply the same rule that you set the administrator and also apply to publishers? just cocultar the separdor if I place a visa in admin and it works why not fuciona for other members who have less power management?

**Comment by bueltge** [comment]
Hi Sylvia.
I have understand, that you allow the Visual Composer for other roles, right?
If the plugin allow this not inside the default, then it is possible to add the capability to the roles. Ask the VC team for this requirement, you buy support for the plugin.
With Adminimize can you hide areas, menu items. If you will hide a Menu Item of the VC plugin, then is no custom source necessary, it is automatically inside the settings page of Adminimize, maybe after update option.

**Comment by SylviaDD** [comment]
Hi Frank
Yes, I want to be equal to the picture you sent me the admin without serarador VC visible paa all other users. If I check for the admin and is ok when I check to the editor should also focus ok (no visibility)
You understand what I mean?
to send you the access can you help me?

**Comment by bueltge** [comment]
Yes ,mail me a access and I will see.

**Comment by SylviaDD** [comment]
I sen you ;) thanks a lot

**Comment by SylviaDD** [comment]
thanks a lot ;) 

Admin URL : http://beerural.pt/wp-admin/
Admin Username : admin.bee
Admin Password : bee.sabores

-- 
e-saudações.
Sílvia Patrícia

 9191 88 978
 http://dinamica-digital.net___________________________________________
[2]
o    Marketing e Publicidade Online
o    Actualização de Websites através de BackOffice | Páginas Sociais 
o    Alojamento Web - Hospedagem | e-Mail | Domínios
o    Design - Web Sites | Blogues | Lojas online 
 [3] 

A 2016-03-04 14:33, Frank Bültge escreveu:

> Yes ,mail me a access and I will see. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/bueltge/Adminimize/issues/21#issuecomment-192303613
[2] http://dinamica-digital.net_______________________________________
[3] http://dinamica-digital.net

**Comment by SylviaDD** [comment]
for that VC, it is ok now. i resolv like the other site in tha other
time i contact-you. 

is ok thanks, VC 

so help SEO link  in the produtcts i can not hide this link i need your
help ;) 

thanks

-- 
e-saudações.
Sílvia Patrícia

 9191 88 978
 http://dinamica-digital.net___________________________________________
[2]
o    Marketing e Publicidade Online
o    Actualização de Websites através de BackOffice | Páginas Sociais 
o    Alojamento Web - Hospedagem | e-Mail | Domínios
o    Design - Web Sites | Blogues | Lojas online 
 [3] 

A 2016-03-04 07:29, Frank Bültge escreveu:

> Hi Sylvia.
> I have understand, that you allow the Visual Composer for other roles, right?
> If the plugin allow this not inside the default, then it is possible to add the capability to the roles. Ask the VC team for this requirement, you buy support for the plugin.
> With Adminimize can you hide areas, menu items. If you will hide a Menu Item of the VC plugin, then is no custom source necessary, it is automatically inside the settings page of Adminimize, maybe after update option. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/bueltge/Adminimize/issues/21#issuecomment-192160152
[2] http://dinamica-digital.net_______________________________________
[3] http://dinamica-digital.net
