### ISSUE TITLE
Doesn't work after editing user roles

### ISSUE THREAD

**Issue by Ligefrem** [bueltge/Adminimize#25]
Adminimize was working great untill I installed User Role Editor to add the file upload capability to the contributor user role.

After that no Adminimize settings for the contributor and authore roles work. I edited the contributor role using the User Role Editor, but not the author role. So it doesn't appear to be settings stuck in the databse. I even reset the User Role Editor settings, uninstalled it, plus reset adminimize and uninstalled + reinstall this (without reinstalling User Role Editor). It still doesn't work.

Any ideas?

**Comment by bueltge** [comment]
Adminimize check only for the role of each users, the string. If you change the role, then you change the capabilities inside the role. If you don't change the role name, then you haven't changed on Adminimize. But if ou have change the name of a role or add, remove roles, then update the settings of Adminimize and it will rewrite all roles and you see this on the settings page.

**Comment by DonDark** [comment]
I have the same exactly issue this plugin is driving me mad!
I wanted the contributor to be able to post featured images, I installed user roles and now all roles are messed up.

the delete options from db of adminimize doesn't not work.

I tried all but restore from yesterday.

that's my last option as I did a lot of work today.

Someone solved it?

**Comment by bueltge** [comment]
@DonDark do you have a access for me, that I can see the problem and maybe better understand?
What is your goal? this > I wanted the contributor to be able to post featured images.
Do you have change the role? With which plugin do you have change the roles, also the capabilties?

**Comment by DonDark** [comment]
OK I solved with a workaround.

What I did, I resonated both plugins on my dev site. Then I installed the editor roles in another websiste to check the default setting. I copy those to my dev site.

So now contributor is back to normal.
I created a new role with editor roles and I used adminimize for that role.

crazy stuff

hope I've helped

**Comment by bueltge** [comment]
If you add new roles, then will Adminimize also work with this. But the capability inside the roles is not in the focus from Adminimize. Adminimize check always and only for the role name, string.

**Comment by DonDark** [comment]
That wasn't the issue. I didn't had any other role plugin except Adminimize. I just installed editor roles after.

Anyway problem solved :)

**Comment by DonDark** [comment]
To clarify better: the issue was not with the Adminimize plugin, this plugin "reads" the user role so if the user role is already edited by another plugin might cause issues.

Both plugins are really good for different use.

Adminimize gave me the chance to hide or show every single line of code inside the admin page so can't complain about it. Specially cause is a free plugin.

Had to add this post cause reading it back seemed like a bad feedback for this plugin and it's not.

**Comment by bueltge** [comment]
Thanks for more background.
