### ISSUE TITLE
0 byte exsport file

### ISSUE THREAD

**Issue by bibi-babi** [bueltge/Adminimize#26]
hi,
wen exsport option the plugin save a file of 0byte and not option.
I dismis all plugin on the site except adminimize, but the problem dont'change . the problem persist from version 1.8.4

Now i need work on the my site test and trasferm the date on stable site.
I have very problem to report al silge option (10 personal secion ....)

The last save corect is on date: adminimize_export-2015-02-24_22-03-21.
i thins that the problem is with new version of WP.. I use on stable site the  WordPress 4.1.1  and on the test site WordPress 4.2.2 

you can control the bug.... plzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
thanks

**Comment by bueltge** [comment]
related to #18 

Thanks for the hint. The export is old, not really state of the art. I will switch to a better form. Current is it a default sql export, not longer supported in WP default.

**Comment by bueltge** [comment]
@bibi-babi Please can you download this repository and test the ex/import functions. Thanks for feedback.

**Comment by bibi-babi** [comment]
YESSSSS!


I installed , I tried to unload and reload .
The file contained inside and charging properly .

Kiss ! Today you made a person happy that in these three days he spent so many bug in a very complex site .

One less sicramente makes me happy .
thanks.

P.S. I have not found a plugin that makes what is your so good !!!!
I could handle the admin for many users without your plugin !

**Comment by bueltge** [comment]
@bibi-babi Thanks for the fast feedback and tests! Also many thanks for the praise, helpful for me.
