### ISSUE TITLE
User specific rules

### ISSUE THREAD

**Issue by vicenterusso** [bueltge/Adminimize#27]
Is it possible to have a master user that will always show everything and all others (admin included) have the filters enabled?

In other words: Have a master user (administrator role) that is IGNORED by Adminimize?

The reason I'm asking is because Editors can't access widgets and other content related stuff (and plugins like page builders too) and then I have to give my client an Admin role.

I could tweak it and make a PR, just want to know if it is already planned or what

*Edit: maybe as a palliative sollution, where could I insert a hardcode global ignoring user id?*

**Comment by bueltge** [comment]
Not on default. But you can add custom rules, like a second master and remove the adminimize menu items or areas in the settings page. So have you a default admin and second admin, with restricted views.
