### ISSUE TITLE
Menu item customize under appereance is not deactivated

### ISSUE THREAD

**Issue by schrik** [bueltge/Adminimize#28]
When the option customize (under the apprereance menu is deactivated, this option is not removed from the menu. I have tested in Wordpress 4.2 and 4.3 on 2 different sites.

link for the item is: 
customize.php?return=%2Fwp-admin%2Foptions-general.php%3Fpage%3Dadminimize%2Fadminimize.php

**Comment by bueltge** [comment]
Can you test this version here, I have implement a alternative check for dynamically menu items.
