### ISSUE TITLE
Adminimize not showing menu at mobiles

### ISSUE THREAD

**Issue by ibiza69** [bueltge/Adminimize#31]
Hi, we are using this plugin and it´s just great!

BUT, today at last we finished our website and went to check everthing thru mobile and ... after login into user account, the top user menu that we configured at Adminimize and that works great thru PCs, doesn´t show at mobiles, it only shows the black background of the menu and nothing else.

I´m attaching both screenshots, from a PC navigating the website (shows perfect the user menu configurated with adminimiza) and the MOBILE image, where you can see that the menu it´s not showing at all and that it´s breaking too the HEADER image.

We haven´t got any other admin reorder menus plugin or so, only Adminimize https://wordpress.org/support/plugin/adminimize and AdminTweaks: https://wordpress.org/plugins/many-tips-together

Does anyone know how to solve this problem?

Thanks for your time and any gelp ;)

![mobiles](https://cloud.githubusercontent.com/assets/13764937/10411734/b31967d8-6f6f-11e5-8071-8866d7ea5def.png)
![website](https://cloud.githubusercontent.com/assets/13764937/10411735/b31e6698-6f6f-11e5-8ba2-45394cd046b5.png)

**Comment by bueltge** [comment]
Can you explain your settings. I think it is only a topic from the global area settings. All other options hide areas, no changes. But maybe the topic to change the "howdy" message is a problem.
