### ISSUE TITLE
$mw_adminimize_menu is not array every time

### ISSUE THREAD

**Issue by odie2** [bueltge/Adminimize#32]
Hi,

I've checked my debug.log and found some spam from Adminize plugin:

`[19-Oct-2015 06:18:03 UTC] PHP Warning: in_array() expects parameter 2 to be array, string given in /home/zschocianow/ftp/wordpress/wp-content/plugins/adminimize/adminimize.php on line 901`

I can't give you more details, as in my Activity Log there are no actions for 2 hours forward and backward.

Seems like you should just replace `$mw_adminimize_menu = '';` to array instead of empty string or add `is_array( $mw_adminimize_menu )` in conditional in that 901 line.

Greetings

**Comment by bueltge** [comment]
This should be done with this commit - https://github.com/bueltge/Adminimize/commit/e630d11ba2455cfa7f85dacc9a7e1dba52368c29
