### ISSUE TITLE
Issue with Gravity Forms

### ISSUE THREAD

**Issue by JDam1138** [bueltge/Adminimize#33]
Using Adminimize and Gravity Forms, I have chosen to modify the 'Editor' group to show Gravity Forms along with Posts, Media, Pages and Soliloquy all the others work fine but gravity forms remains hidden, any work arounds? I have everything unchecked for anything Forms related

**Comment by bueltge** [comment]
Do you can add Screenshots, that I can understand the problem much better.

**Comment by JDam1138** [comment]
[Issue with Gravity Forms Not showing.pdf](https://github.com/bueltge/Adminimize/files/36025/Issue.with.Gravity.Forms.Not.showing.pdf)

Hope this helps a little, I've tried updating, deleting all the settings, importing the settings in again, removing all the deactivate options for the editor group (nothing checked). Nothing, can't seem to figure out the issue.

**Comment by bueltge** [comment]
Currently I don't understand the problem. The fild "Role" in this screenshot is hidden? It is a field on the Gravity Form? I think, is on the user-profile page.

**Comment by JDam1138** [comment]
You are totally right, I actually have to modify Gravity Forms to give access to other roles as by default it's set for Admin's only (http://goo.gl/pboeTp). Thank You! Love your plugin by the way, helps out a lot!

**Comment by bueltge** [comment]
@JDam1138 Maybe you like it, that you editor can show the the Gravity Forms menu items? I can't find a problem with Adminimize. GF add his menu items with a custom capability and only the roles, there have this, can see this items in the menu. You can change the capability for each role with the plugin Member as example.
