### ISSUE TITLE
screen option item AKA meta_box

### ISSUE THREAD

**Issue by gine** [bueltge/Adminimize#35]
A lot of new themes give to the users a lot of screen options when you write an article. 

Ony for an example, my contributor have slug, revolution slider options, qode general, qode header, qode title, qode scoll title animations.. and so on.

Yes i can disable this unwanted box by screen settings, but it' only for the user whit who i logged in. 

If i am an administrator and i need to manage a lot of contributors, i think that if you support that possible on your plugin, it would be nice.

This post it's an hint:  http://wordpress.stackexchange.com/questions/56606/how-to-remove-certain-screen-options-and-meta-boxes-from-add-edit-post-type

**Comment by bueltge** [comment]
You can now hide each meta boy for each role, that each role only see, what you want as Administrator. 
Is this not enough, what is your cleat goal. 
Thanks for your explaining reply.

**Comment by gine** [comment]
Screen options unchecked:

![screen_opt_checked](https://cloud.githubusercontent.com/assets/252931/12063532/a0ca4daa-afb0-11e5-90e9-71833298566a.png)

Screen options checked:

![screen_opt_unchecked](https://cloud.githubusercontent.com/assets/252931/12063533/a3e840a0-afb0-11e5-97f1-7a68edeb83a1.png)

As you can see on this print screen a lot of plugin and themes give the possibility to every user to manage the screen on the editor. The user can set or not what he wants see. 

Sometimes the administrator wants that the customs meta_box are hidden because he doesn't want that an user with "editor" or "contributor" level can set something of strange like background or other layout style.

Meta boxe to hide permanently with adminimize:
![meta_box](https://cloud.githubusercontent.com/assets/252931/12063531/9f1f2656-afb0-11e5-93d5-5d7eddd21376.png)

So, plugins and themes don't manage to set a custom screen option for roles, and i'm asking you to manage that. On your plugin, on article editor setting i don't see nothing to do that. Your plugin manage correctly every custom elements in the admin bar and menu sidebar but not the meta_box.

![adminimize_article_editor](https://cloud.githubusercontent.com/assets/252931/12063656/c9b175ca-afb2-11e5-9fb2-d302c3a743f7.png)

To try that you can install revolution slider and try some theme like sahifa or bridge.

**Comment by gine** [comment]
Oh ok.. i managed it. The italian traduction it's not so clear. 

The only problem that remain is that if i put some custom div to hidden with adminimize,  the post screen option remain and there aren't id or class to hide the label too.

**Comment by bueltge** [comment]
Maybe you can use the [attribute selector](http://www.w3schools.com/css/css_attribute_selectors.asp) in css. The option have the label tag in the admin area, like `<label for="dashboard_quick_press-hide"><input class="hide-postbox-tog" name="dashboard_quick_press-hide" type="checkbox" ... `

With the css selector `label[for=dashboard_quick_press-hide]` can you hide this areas.
