### ISSUE TITLE
It does not work anynore.

### ISSUE THREAD

**Issue by anzwers** [bueltge/Adminimize#36]
Dear Frank, first of all sorry for my bad english, I am italian.
This is the scenario.

I installed the puglin 2 month ago and it works perfectly!
Then, after some time I modified some options but I have seen that nothing "change" anymore... I could not hide new unnecessary items under authors and so on.
Ok, so I deleted the db (with uninstall Options button).... but surprise... nothing change... I could see always the same few items (under authors) so the old hide items ramain hidden and those visible remain visible.

So I removed the plugin, but no difference. No new links, no new items.... my author backend is always the same, like the firt time I setup and saved (2 month ago) the options under the plugin.
Then I have tried to install the beta, the 1.9.0-RC2 version.... but no way, under author I see always the same items.

In a few words, I can clean the db, I can select everything or not (and save, of course), I can remove the pluging but nothig change.
If you need I can send you the admin details, thank you!

Augusto

**Comment by bueltge** [comment]
A admin access would be fine. It is much easier for me to see the problems. 
Please install the current test version 1.9.0, I have a lot of changes in this version. 

Please send me also a login for a author role, so that I can check via admin and test with the author. Thanks. 

Best.

**Comment by anzwers** [comment]
Dear Frank, how can I send you the wp account data in a private mode?
Thanks!

Augusto

**Comment by bueltge** [comment]
Mail to frank@bueltge.de please.

**Comment by anzwers** [comment]
Thank you, I wrote you from my email: agoago@mail.com, just you know. Ciao!

Augusto

**Comment by bueltge** [comment]
switch to mail-support.
