### ISSUE TITLE
Fatal error (is_plugin_active_for_network()) on multisite installs

### ISSUE THREAD

**Issue by dyron** [bueltge/Adminimize#37]
Hi,

there is an fatale error on multisite installs:

`Call to undefined function is_plugin_active_for_network()`

Please add before line 1272: `if ( is_multisite() && is_plugin_active_for_network( MW_ADMIN_FILE ) ) {`
```
	if ( ! function_exists( 'is_plugin_active_for_network' ) )
		require_once( ABSPATH . '/wp-admin/includes/plugin.php' );
```

**Comment by bueltge** [comment]
Do you have usage  last version of this repo, github, 1.9.0-RC? 
If no, please test with the new version, I will release this in view days.

**Comment by dyron** [comment]
I got it via `composer update` and the file header says 1.9.0-RC. I also tested a github master download with the same result.

**Comment by bueltge** [comment]
Hi @dyron 
please test again. I have fixed this topic and centralize the function to check this status on Multisite.
Please use the download of the master branch, the Composer file have the last stable as version inside.
Thanks for your feedback!

**Comment by dyron** [comment]
Hi,
yeah, the latest master version works.
Besides that it seemed a bit weird after running `composer update` wordpress kept the message Adminimize needs to update. Anyway, looking forward for the new composer release. ;)

**Comment by bueltge** [comment]
Thanks for your feedback and helping hands!
