### ISSUE TITLE
Hide some Pages for some Roles

### ISSUE THREAD

**Issue by bueltge** [bueltge/adminimize#39]
Pages are something that dont change for years. Problem is some change, some not. Some are build by different shortcodes for design/layut and content, and is not good to give other than Admins access to them.

Can you make a new option in Adminimize to hide (specific, not all) Pages (not Posts) from some roles ?

If it can help you this snippet hide them from view (they are still editable if accessed, could not find any way to disable them totally from Editors, etc)

``` php
add_action( 'pre_get_posts' ,'exclude_this_page' );
function exclude_this_page( $query ) {
        if( !is_admin() )
                return $query;
        global $pagenow;
        if( 'edit.php' == $pagenow && ( get_query_var('post_type') && 'page' == get_query_var('post_type') ) )
                $query->set( 'post__not_in', array(23,28,30) ); // page id
        return $query;
}
```

source: https://wordpress.org/support/topic/feature-request-hide-some-pages-for-some-roles

**Comment by Sarizahzabie** [comment]
Hello bueltge,

Firstly, its the one of the best things around, congrats. 

I would really like to suggest something simple as an add on. It would be nice if there is a function for Super Admin account to have like a password or "special config key" to open protected configuration page so they can modify all of the settings. This will require Adminimize configs page to have an option to be hidden on the "Menu Option" or on what ever it may fit in, even for Super Admin accounts. It would be great to hand out finished projects while making sure the client won't tamper with the initial settings especially WP basic settings and other related plugins. It is ok if they know we are using Adminimize and it would be a bonus if we can see when was the last time any modification was made on Adminimize setting.

Yes, there are other option like using role and capabilities plugins but different plugins will have different capability IDs. And you know WP Roles are something we would really love not touch upon too much. Everyone is pretty much comfy with the usual roles within WP.

Its just what I think is the best for Adminimize. Just my 10 cents tho. All the best!

**Comment by acuatoria** [comment]
I have newsletter plugin installed and smtp settings subitem not appear in adminimize.
I think I need this solution, but I don't know how to. I have tested to add custom slug in adminimize unsuccesfully. I need to hide this subitem.

**Comment by bueltge** [comment]
Hi @acuatoria PLease open a new issue, add screenshots, that I understand your problem. I think you need no code, only a custom slug for the menu items.

**Comment by chapsmurf** [comment]
Hi,

I have exactly the same problem as @acuatoria had, with the same plugin. I am wanting to restrict (hide) various sub menus from a certain role. I can hise the menus in the main left hand WP menu, but the plugin has sub-menus on it's main page and those are the ones I am trying to block. 

I have tried to creating custom slugs but they don't work. Maybe I have not done this correctly.

**Comment by bueltge** [comment]
@chapsmurf Which plugin add this menu items? It is possible for me to try this, is the plugin for free, so that I can test it?

**Comment by chapsmurf** [comment]
Hi @bueltge. 

Thanks for your reply. 

The plugin is called Newsletter (https://wordpress.org/plugins/newsletter/) and this is free (although there are paid additions of course). The free plugin will load all of the menus you can see on the image I attached. Essentially I am looking to block any link that will allow another user access to the subscriber information, but once you find a way of blocking one of the sub-menus, I am sure I can replicate this for others.

**Comment by bueltge** [comment]
Hello @chapsmurf 
I have installed the plugin. At first, all menu items are only visible, accessible for Administrator.
However I can hide menu items via Adminimize, I active the items and there are not visible.

See the right back end is without the last two menu items like the settings from the left screen, the settings area of Adminimize.
![image](https://user-images.githubusercontent.com/133425/42510721-1bf37710-8450-11e8-8d37-c5d741e60c15.png)
