### ISSUE TITLE
C F 7 doesn't hide

### ISSUE THREAD

**Issue by Vasco39** [bueltge/Adminimize#40]
Hi all, 
I've an issue to hide the CF7 menu item on the admin section.
If I select the flag the menu doesn't disappear.

Vasco

**Comment by bueltge** [comment]
Can you test this with the version from this github repo? I think it is fixed here.

**Comment by Vasco39** [comment]
Yes nice, now it works!!

Thanks
Vasco

**Comment by bueltge** [comment]
Thanks.
