### ISSUE TITLE
Slow Performance

### ISSUE THREAD

**Issue by treiber** [bueltge/Adminimize#42]
As soon as I activate Adminimize I get very bad performance. The page loads 3, or four Items in the left navigation an then just loads for about 3 to 10 seconds. Disabling the Plugin solve the issue.
I'm on the latest 1.10.0 on an Ubuntu 14.04.4 with PHP 5.5.9.

It's a very long first GET Response. As far as I can tell, the Server (with Apache2) is working fine.

**Comment by bueltge** [comment]
Do you are logged in? 
Do you have the problems on front end or back end? 
Thx.

**Comment by bueltge** [comment]
I have only one check via GET to identifier the settings page of the plugin. Maybe this is a problem, but currently I have same information from other users or in my different environment. 
Thanks for your help to identifier the problem.

**Comment by treiber** [comment]
Logged in on both Front and Backend!

**Comment by bueltge** [comment]
Can you test please, that it is the same problem on front end, if you are not logged in. 
Thx.

**Comment by treiber** [comment]
The Problem does not seem to occur if I'm not logged in (the Admin bar is not shown)
<img width="1438" alt="with-plugin-active" src="https://cloud.githubusercontent.com/assets/5053591/13262665/3fce4aac-da66-11e5-9a91-440f0b338ff6.png">
<img width="1440" alt="with-plugin-inactive" src="https://cloud.githubusercontent.com/assets/5053591/13262666/3ff2f438-da66-11e5-866f-7cb25a75dae1.png">

**Comment by treiber** [comment]
I'm running the latest 4.4.2 of Wordpress btw.

**Comment by bueltge** [comment]
I have always good values on load in the web inspector. Can you validate, that no other plugin, theme function is the problem and break the load?
But I will also check in the deep.

**Comment by bueltge** [comment]
I have also analyzed via trace, see the screenshot. It is potential for improvements, but the value is not high, much smaller as lot of other topics.
![webgrind](https://cloud.githubusercontent.com/assets/133425/13487139/c28eeb2e-e117-11e5-95cc-41ee10f04803.png)

**Comment by bueltge** [comment]
I have add a object cache for get options, it is helpfull, see the screenshot
![webgrind2](https://cloud.githubusercontent.com/assets/133425/13499033/d02412ce-e15c-11e5-8bc6-d6dc7045f695.png)
