### ISSUE TITLE
Unable to revert back to original

### ISSUE THREAD

**Issue by plsgibchance** [bueltge/Adminimize#44]
Dear developer, 

I am unable to remove the settings that I have set for adminiszer. For instance, I use adminimizer to deactive "appearance " and "post" for my authors and now I am not able to let these items appear on their menu. Please help!

#### Version Information
* WordPress: 
* Multisite: true/false
* Adminimize: 

#### Steps to Reproduce
1. 
2. 
3.

**Comment by bueltge** [comment]
Please can you describe the problem much better. 
It is possible to deactivate the checkboxes on the settings page?
Can you remove all settings via option of the settings page, the last area to remove all options?

Different options are personal options on the user meta data, if you had deactivated this for a role, WP save this also in the global options of the user and each user must activate this, via "Screen Option", the core settings on each page in the back end area.
