### ISSUE TITLE
Saving does not apply for custom role

### ISSUE THREAD

**Issue by mr910** [bueltge/Adminimize#45]
#### Version Information
* WordPress: 4.5.2
* Multisite: false
* Adminimize: 1.10.4

#### Steps to Reproduce
1. Create new role - 'Site Owner' was used in this case. Creation was doing using AAM
2. Custom role shows in Adminimize and some options save while others do not. Specifically the dashboard.
3. Disabled AAM and the issue is still present

#### What I Expected
Hiding dashboard and menu items

#### What Happened Instead
Settings do not save

**Comment by bueltge** [comment]
Can you check, if you create a custom role without whitespace, like  'Site_Owner'. It is the same problem. Different Role Creator plugins have problem in this topic.
