### ISSUE TITLE
Unable to revert back to original setting and layout.....

### ISSUE THREAD

**Issue by Stratozsphere** [bueltge/Adminimize#46]
#### Version Information
* WordPress: Version 4.5.3
* Multisite: false
* Adminimize: 

#### Steps to Reproduce
1. Install Adminimize
2. Set the settings to turn off elements for Write options - Products
3. Elements turned off, and it works OK for woo commerce products
4. Turn Elements back on, and it won't revert to original setting and layout
5. Have used the delete options button to try and revert and removed plugin, same issue

#### Screenshot or Video
https://youtu.be/9sv7IlthD4E

**Comment by bueltge** [comment]
Hey.
After reload the page, after remove all settings to the "product" open the "screen options" on top, right and check, if the area, the Meta Box for this current user active.
WP save this on the user profile. If you hide areas, WP remove is a default for the current user. A re-activation of this section is necessary.
Thanks for feedback and also a praise for the video, relly helpful for me to understand.

### Hint about removing areas.
The plugin Adminimize have only on default the standard selectors to remove areas. Especially on plugins with custom post type and custom enhancement, like WooCommerce, give it much more selectors, changes in this areas. You cna find this via Webinspector, like F12 in Chrome, and add this selectors as custom options to the Adminimize settings.

**Comment by Stratozsphere** [comment]
Thank-you Bueltge,

Much appreciated. One more question. With Adminimize if I wanted to turn off the main text area, how would I do that? I am not familiar with using the web inspector.

![screen shot 2016-07-07 at 7 17 21 pm](https://cloud.githubusercontent.com/assets/13617421/16648466/8debf196-4477-11e6-8630-ed373690f716.png)

**Comment by bueltge** [comment]
You should a custom option on this custom post type.

Selector is `#postdivrich` The id of this area div.
In the custom options of Write Options -Products:
left textarea: `#postdivrich`
right textarea: Editor of Products (as example)

The entries are in the same line.
Save this settings and after load the settings page again, you see this option and can select for different roles.

**Comment by Stratozsphere** [comment]
Thanks so much!!!!

**Comment by bueltge** [comment]
Welcome.
