### ISSUE TITLE
Bug: 'Page -- HTML Editor Button' options hide 'Post -- HTML Editor Button options'

### ISSUE THREAD

**Issue by kcloud** [bueltge/Adminimize#47]
#### Version Information
* WordPress: 4.6
* Multisite: false
* Adminimize: 1.10.6 

#### Steps to Reproduce
1. Select an option from Page -- HTML Editor Button for a user role
2. Navigate to create a new post
3. User role will be unable to see content area (textarea is hidden). This makes it appear as if the post is gone when editing an existing post, or that edits are not being made if creating a new post.

#### What I Expected
I updated Wordpress and the plugin, expecting no setting changes.

#### What Happened Instead
After updating, page selections for HTML Editor Button caused the text area of the Posts (New Posts, Edit Posts) to be hidden. This may be related to the divs used, as well as new changes to the plugin. A temporary fix is available by removing the option setting.

**Comment by bueltge** [comment]
I have tested this and it works really fine, on post and page. Maybe you have more information for me, please feel free to reopen the issue.
