### ISSUE TITLE
Unable to save setting for CTPs

### ISSUE THREAD

**Issue by SamThilmany** [bueltge/Adminimize#50]
#### Version Information
* WordPress: 4.6.1
* Multisite: false
* Adminimize: 1.10.6

#### Steps to Reproduce
1. Create CTP
2. Open Adminimize
3. Try to save changes

#### What I Expected
I expected to be able to save the settings as I did for the built in post types and other settings.

#### What Happened Instead
I am unable to save the settings. After saving, all the checkboxes were unchecked again.

#### What I Tried
I tried with a self coded CPT and with one made with the `Custom Post Type UI` from WebDevStudios. It doesn't work for neither of them.

**Comment by bueltge** [comment]
Hey Sam,
can you check again this with this CPT - https://github.com/bueltge/archive
only for testing. The plugin leave no data in the database, if you restore the post from Archive to the pots back after testing.

Also, often is the saving of to much data in the settings page a problem in different server configurations. Please see [this topic](https://wordpress.org/support/topic/menu-options-values-lost-upon-upgrade/) for helpful answers.

**Comment by SamThilmany** [comment]
Hey Frank,

Thanks for your hint to check out the existing topic. I just increased the `max_input_vars` in the `php.ini` to 3000 and it works well.

**Comment by bueltge** [comment]
Great. Thanks for the feedback. 
How do you have increased the value? Can you explain this here for other readers.

**Comment by SamThilmany** [comment]
Yes, of course.
I have extended the `php.ini` by the following entries:
```
max_input_vars = 3000
suhosin.post.max_vars = 3000
suhosin.request.max_vars = 3000
```
If the entries already exist with other numerical values, the numerical values should only be replaced!

If you don't have access to the `php.ini`, you can try to add this to the `.htaccess` of your WordPress installation:
```
<IfModule mod_php5.c>
 php_value max_input_vars 3000
</IfModule>
```

**Comment by bueltge** [comment]
You have access to the php.ini, great. Thanks for your feedback.
