### ISSUE TITLE
Prevent access to profile.php, tools.php directly (via url)

### ISSUE THREAD

**Issue by pisces72** [bueltge/Adminimize#51]
#### Version Information
- WordPress: 4.6.1
- Multisite: false
- Adminimize: 1.10.6

Hello,

Can I use this plugin to prevent ordinary users from accessing for example wp-admin/profile.php and tools.php

I can disable the menu, but they can still type the URL directly.

I am currently using this workaround:

``` php
function disable_page() {

    if ( ! current_user_can('administrator') ) 
    {
        wp_die( 'Access denied.' ); 
    }

}
add_action( 'load-profile.php', 'disable_page' );
add_action( 'load-tools.php', 'disable_page' );
add_action( 'load-user-edit.php', 'disable_page' );
```

Thanks for this great plugin!

**Comment by bueltge** [comment]
Hey @pisces72 
you have right. The plugin hide currently only, no check or todo to prevent the access.
For a refactoring of the plugin is it a requirement in my list, but I found not enough time for this work.
But maybe I include a simple solution, like your idea for each page slug of the admin pages.
