### ISSUE TITLE
js errors when disabling admin bar front end features

### ISSUE THREAD

**Issue by S-Hodgson-MMOARgames** [bueltge/Adminimize#52]
#### Version Information
- WordPress:  4.6.1
- Multisite: false
- Adminimize:  1.10.6
#### Steps to Reproduce
1. Install WP 4.6.1
2. Install Aminimize 1.10.6
3. Disable Admin Front end feature "Howdy, mmoargames admin"
#### What I Expected

No errors in console.
#### What Happened Instead

```
admin-bar.min.js?ver=4.6.1:1 Uncaught TypeError: Cannot read property 'addEventListener' of null
d   @   admin-bar.min.js?ver=4.6.1:1
(anonymous function)    @   admin-bar.min.js?ver=4.6.1:1
```

Seems to happen for a few others as well.

**Comment by bueltge** [comment]
Hey.

Do you have remove the Admin Bar completely for a role, right? Please add also your settings in Adminimize, I will check this also. Adminimize removes the admin bar include his requirements for a better performance, if is not necessary. Maybe this is the problem and I will fix this later.
Best regards.

**Comment by bueltge** [comment]
It is not possible for me to retrace this issue. No js errors.
