### ISSUE TITLE
Warning: shell_exec() has been disabled for security reasons in ...

### ISSUE THREAD

**Issue by gabrielcello** [bueltge/Adminimize#59]
#### Version Information
* WordPress: 4.6.1
* Multisite: false
* Adminimize: 1.11.1

#### Steps to Reproduce
1. After the last update there is an error in the footer of the site

#### What I Expected
I expected to find no error

#### What Happened Instead
Show this error:

**Warning: shell_exec() has been disabled for security reasons in /web/htdocs/www.***************/wp-content/plugins/adminimize/inc-setup/admin-bar-items.php on line 101**

#### Screenshot or Video

![area riservata docenti e personale ata i c boville ernica a s 2016 2017 2016-11-26 22-56-26](https://cloud.githubusercontent.com/assets/24195458/20644160/b1f51ac6-b42b-11e6-8bd7-083655e52ebb.jpg)

**Comment by bueltge** [comment]
The error should now fixed, please can you install manual this version from github - Download here https://github.com/bueltge/Adminimize/archive/master.zip and give me feedback.
Thanks!
