### ISSUE TITLE
Loading of the Media Library isn't working anymore

### ISSUE THREAD

**Issue by Joalmama78** [bueltge/Adminimize#63]
Hello Mr. Bueltge,

Thank you for the great plugin! I’m excited!

Unfortunately, I have the same problem as described above. I’ve already tried to remove all the hooks that have to do with “media” or “upload”. Unfortunately without success.

I've removed all checkmarks as an administrator too, but I can't see the media in the media gallery anymore. Only when I deactivate the plugin, the overview appears again.

To upload screenshots here wouldn’t be appropriate in my case . Would it be possible to give you access to my backend?

It would be very nice if you could take a look. In the meantime, however, I will try to solve the problem and report you if I will have success.

Thanks in advance! I am looking forward to your reply.

**Comment by bueltge** [comment]
Access - yes, please, maybe I can see a error on the console and also the settings. Really great and helpful.
Please send it to my priv. mail frank AT bueltge DOT de

**Comment by Joalmama78** [comment]
Hi, thanks for your support! You'll recieved an e-mail in a few minutes. :)

**Comment by bueltge** [comment]
@Joalmama78 Which mail can I use to communicate with you, please write me a mail for question/answer.

**Comment by bueltge** [comment]
There was a problem with the active debugging option of the plugin. The debugging helper add a script, that log different data in the console of the browser and this is a problem with background, ajax response.
