### ISSUE TITLE
Unable to hide "Toolset plugin" menu in backend

### ISSUE THREAD

**Issue by olybop** [bueltge/Adminimize#72]
![sans titre-2_r1_c1](https://user-images.githubusercontent.com/274494/30113455-0d35165c-9315-11e7-9d2b-ce4d9e0bae54.jpg)
Hi there !
I'm using "user role editor" to create new one, after i configure to hide toolset on admin menu but it's not working. All the other works well.

#### Version Information
* WordPress:  4.8.1
* Multisite: false
* Adminimize: 1.11.2 
* Toolset type: 2.2.16

![sans titre-1_r1_c1](https://user-images.githubusercontent.com/274494/30113390-e173ad80-9314-11e7-9ce4-1eaa259f3a8f.jpg)

**Comment by bueltge** [comment]
Hi @olybop 
That will not work only for this menu item? If yes, it is a additional plugin, not the WP Core. I need access to this plugin, have you an link. Maybe its change the slug of the menu item, but this is only visible for me if I get access to your admin area or the plugin to test in my environment.

**Comment by olybop** [comment]
hi @bueltge 
thanks for your response, i just send you an email ;)
Best

**Comment by bueltge** [comment]
After analyze, the slug of the menu item of this plugin is different for the user roles, see the screenshot below.
![image](https://user-images.githubusercontent.com/133425/30115861-3d2f0f28-931c-11e7-8ac3-1cb0ac6d1278.png)

So you have only the chance to add this slug `wpcf-cpt` to the "Own Options" of the menu items.

Best.

**Comment by olybop** [comment]
Top ! Thx for all, i'll close the topic.

**Comment by bueltge** [comment]
Add the solution to the wiki - https://github.com/bueltge/Adminimize/wiki
