### ISSUE TITLE
Disabled menu item changes if a plugin adds a new menu item above it

### ISSUE THREAD

**Issue by Garconis** [bueltge/Adminimize#73]
Lately, I've been noticing a pretty annoying aspect of this plugin. I'm not sure if it's a conflict with another plugin we have installed too, but here it goes...

We have numerous installs, and often use Adminimize to hide the WooCommerce > Extensions menu item (and obviously to prevent access to that page).

So we deactivate (by checking the boxes) that menu item for all Roles. But if/when a NEW plugin is added, that also adds its own menu item above the WooCommerce > Extensions one, then the Extensions menu item is no longer disabled.

By going into the Adminimize settings, we see that the checkboxes are no longer assisgned to the Extensions item, but the one above it.

Somehow, it seems this plugin is working based off of the "count" of the menu... rather than some other means. This then causes the wrong menu item to become disabled, when a new one is added.

**Comment by bueltge** [comment]
Hi @Garconis Please can you check in this behavior the slug of the menu item. You find it on the item entry in the settings page. Important helpful for me is the difference after activation a plugin, so that it not work. Thanks for enhance the issue with this really relevant information.
