### ISSUE TITLE
Showing Disabled Plugin Menu

### ISSUE THREAD

**Issue by 2nevergiveup** [bueltge/Adminimize#74]
#### Version Information
* WordPress: 4.7.7
* Multisite: false 
* Adminimize: 1.11.2

#### Steps to Reproduce
1. Install Visual Composer
2. Disable Visual Composer on certain User Role
3. Access via restricted User role, and you will see the Visual Composer Menu tab still

#### What I Expected
After disable User role from Visual Composer, I am expecting restricted users won't be able to see the menu in dashboard?

#### What Happened Instead
After disable User role from Visual Composer, restricted users see the disabled plugin menu in dashboard.

#### Screenshot or Video
http://recordit.co/6hhmhHAfM1

**Comment by bueltge** [comment]
The plugin Visual composer is really different, please try this https://wordpress.org/support/topic/hide-visual-composer/ and give feedback, I think this should work for you.

You find this hint and other ones in the Wiki of this plugin - https://github.com/bueltge/Adminimize/wiki
