### ISSUE TITLE
Notification message showing on top 

### ISSUE THREAD

**Issue by 2nevergiveup** [bueltge/Adminimize#75]
#### Version Information
* WordPress: 4.7.7
* Multisite: false 
* Adminimize: 1.11.2

#### Steps to Reproduce
1. Install woocommerce  or any plugin that will pose a notification on top
2. login via restricted users' account
3. you will see error notification on top

#### What I Expected
If users do not have access to certain plugins and its features, I believe such messages/notifications should only be shown to admin?

#### What Happened Instead
restricted users can see messages/notifications from restricted plugins

#### Screenshot or Video
<img width="1374" alt="screen shot 2017-11-01 at 6 40 20 pm" src="https://user-images.githubusercontent.com/33302603/32306393-3eb08fbe-bf38-11e7-9e13-8c806bee3962.png">
http://recordit.co/fEnR02U8ki

**Comment by bueltge** [comment]
Currently remove the plugin not all or different notices from other plugin.
You can use the function of custom options to solve this - see the how to on  https://github.com/bueltge/Adminimize/wiki

Alternatively you can try the global option to remove all notices, see "Global options" Area of the settings page. 
Thanks for your feedback and tests.
