### ISSUE TITLE
Ignore menu options when viewing Adminimize settings no longer works

### ISSUE THREAD

**Issue by Relequestual** [bueltge/Adminimize#77]
Adminimize settings page says "The Adminimize settings page ignores the Menu Options below and displays the menu with all entries" - This worked like a charm previously, but after an update of the plugin, I can no longer see any of the hidden menu items. This means I can't see the plugin version either!

#### Version Information
* WordPress: latest as now
* Multisite: false
* Adminimize: latest as now

#### Steps to Reproduce
Access settings/Adminimize

#### What I Expected
See all menu items

#### What Happened Instead
Do not see all menu items

#### Screenshot or Video
N/A

**Comment by bueltge** [comment]
Hi @Relequestual 
Please can you try this current development version?
Download: https://github.com/bueltge/Adminimize/archive/master.zip
Overwrite all file sin your current install of the plugin.

**Comment by Relequestual** [comment]
Thanks @bueltge 
Sure, I'll give that a try and repot back.

**Comment by Relequestual** [comment]
Hey @bueltge - This update seems to have fixed the issue. Had to do a hard refresh and re-save settings, but works as expected now.

I had a look see and the change you made looks correct. =]

**Comment by bueltge** [comment]
Thanks a lot for your feedback. I will release this version in the next view days.

**Comment by Relequestual** [comment]
Hold on a second...
The plugin now doesn't seem to do what it's intended.
I also tried to download and restore the settings and was met with the following error: "It is not possible to find a file in /tmp/phpmWLzkk"

**Comment by bueltge** [comment]
Do you try this on a installation on a web, online or a local apache?

**Comment by Relequestual** [comment]
Live host. I don't have a local environment for this site. I don't do wordpress as part of my day job anymore =/

**Comment by bueltge** [comment]
Can you again the new version. I think your server get not enough information about the file. The check for the right file type is wrong and it is not necessary to import.
Thanks for your help!

**Comment by Relequestual** [comment]
I can have a look, but I'm unsure of timescale! If you haven't heard from me in 2 weeks, please mention in a follow up comment to remind me? Thanks.

**Comment by bueltge** [comment]
I have release this change today, should be fixed. If not, please feel free to reopen the issue.
