### ISSUE TITLE
Lost child menu - only show one child item in menu

### ISSUE THREAD

**Issue by vanloc0301** [bueltge/Adminimize#78]
#### Version Information
* WordPress: 4.9.1
* Multisite: false
* Adminimize: 1.11.3 

#### Steps to Reproduce
1. I install a plugin with the name: `Mua hang nhanh` - to quick buy a product in Wordpress.
2. I don't want to deactivate this menu and child menu of this plugin.
3. Problem is it auto-hide two child menu, keep only one menu of this plugin.

#### Capture:

You can see, I do not tick any checkbox to deactivate:

![capture](https://user-images.githubusercontent.com/4168981/33783410-3dae828c-dc8f-11e7-8266-838134323038.PNG)

I tried to log in to account have full access to this plugin (I do not deactivate any item in this plugin).

You can see:
![capture](https://user-images.githubusercontent.com/4168981/33783538-cc822dd8-dc8f-11e7-994f-05ffa667d250.PNG)

Two item is lost:
![capture](https://user-images.githubusercontent.com/4168981/33783620-1be1e81e-dc90-11e7-9408-ad4875360ab0.PNG)

Have some issues with me. I think the problem at ID of the plugin.

Have any simple method to resolve my problem?

With slug - custom slug or I must contact to the producer of this plugin to receive support.

```
Menu                                                             Slug
Mua Hàng Nhanh                                                mua-hang-nhanh
Mua hàng nhanh                                                mua-hang-nhanh(__0)
SMTP Setting                                                  smtp-setting(__1)
Sửa đơn hàng                                                  muahangnhanh_process(__2)
```

**Comment by vanloc0301** [comment]
Hi @bueltge, I added the Slug of each item into my issues.

**Comment by bueltge** [comment]
Can you try to hide only sub-items, without the item `mua-hang-nhanh`, works that?
It is also possible to get this plugin, so that I can debug in my environment.

**Comment by vanloc0301** [comment]
@bueltge 
I don't want to 'Adminimize' hidden any item (or sub-items) in this plugin. 

I don't tick any items, but it still was hidden.

I sent email with attachment file to your email: frank@bueltge.de

Thank you very much.

**Comment by bueltge** [comment]
The mail is arrived and I will check this with your plugin.

**Comment by bueltge** [comment]
Was an capabilitity topic, the plugin have only `managed_options` cap in his role so that an access on default is not possible for an editor-role.
