### ISSUE TITLE
Some menus that are not checked do not appear to role

### ISSUE THREAD

**Issue by marlaaragao** [bueltge/adminimize#83]
Version Information
* WordPress: 4.9.2
* Multisite: false
* Adminimize: 1.11.4

Hello, some menus that I did not check (the case is the Monster Insights plugin menu and submenus) doesn't appear to any role that is not the Administrator. I tried adding the custom slugs and NOT cheking them and it didn't work as well.

I would like to know if there is any solution for this. I tried finding in the internet but with no success.

Thank you!

Below some images: the options NOT marked in Adminize and the menu that appears to the user that has the role 'Editor'.

![adminize options](https://user-images.githubusercontent.com/7109504/35275780-fb3a0018-0027-11e8-9da2-d1de9d045b40.png)
![menu editor](https://user-images.githubusercontent.com/7109504/35275781-fb5e4d06-0027-11e8-9e5e-407c5933e09a.png)

**Comment by marlaaragao** [comment]
Sorry, my bad, the problem was with some other permission settings. Thanks for the amazing plugin!

**Comment by bueltge** [comment]
Thanks for your feedback to clarify this.
