### ISSUE TITLE
Can't import settings json

### ISSUE THREAD

**Issue by KSVQ** [bueltge/adminimize#85]
#### Version Information
* WordPress: 4.9.4
* Multisite: false
* Adminimize: 1.11.4

#### Steps to Reproduce
1. Export settings json in export/import options
2. Import settings in export/import options of a new site

#### What I Expected
A straight forward import of settings

#### What Happened Instead
500 error | /wp-admin/options-general.php?page=adminimize-options

#### Screenshot or Video
Blank Page

**Comment by bueltge** [comment]
The 500er error after import? Go to settings again, the settings are not imported?

**Comment by KSVQ** [comment]
They are not imported. No. import fails.

**Comment by bueltge** [comment]
I tried this for now in different local installs and also customer installs, no errors or problems. Maybe you have more error information for me? Please active the [WP_DEBUG](https://codex.wordpress.org/WP_DEBUG) constant inside your wp-config.php and try it again, maybe we get more informations about errors.

**Comment by KSVQ** [comment]
Try adding a custom setting maybe.

**Comment by KSVQ** [comment]
I get this:
`Fatal error: Class 'finfo' not found in /home/occcconf/public_html/api/2018/wp-content/plugins/adminimize/inc-setup/import.php on line 51`

**Comment by bueltge** [comment]
This class is since php 5.3 on core. Maybe you have an older php version, can you check this?
see https://secure.php.net/manual/en/class.finfo.php

**Comment by KSVQ** [comment]
Running on PHP Version 5.6.33

Hm...

**Comment by KSVQ** [comment]
You know,, I am sorry for the bother. This is probably related to some issues with our server and not with your plugin. I just successfully imported a settings file into a different instance of wordpress (all same versions).. If I find out exactly what the issue is I'll update you.

Thank you for trying to help :)

**Comment by bueltge** [comment]
Great for me, bad for you. Thanks for this feedback.
