### ISSUE TITLE
Wordpress offer to login via wordpress.org

### ISSUE THREAD

**Issue by AurelTristen** [bueltge/adminimize#88]
#### Version Information
* WordPress: 4.9.4
* Multisite: false
* Adminimize: 1.11.4

#### Steps to Reproduce
1. Go to [yourwebsite]/wp-admin or your login page (while logged out)
2. Observe new login option

#### What I Expected
I would like to be able to hide/skip this offer to login via Wordpress.org

#### What Happened Instead
Wordpress updated and added a feature that Adminimize doesn't yet block

I love your plugin! Thanks so much for putting it out there! But WP has added a new feature that name-drops WP in a very obvious way. It's a little box that replaces the login screen with an offer to allow you to login through wordpress.org. Not only does this break my attempt at white-labeling WP, but it is annoying and confusing for my clients. Do you think you could find a way to block it with Adminimize?

Thank you!

**Comment by bueltge** [comment]
Hi @AurelTristen 
Can you add a screenshot of the login via w.org; the default of an WordPress install don't have this option. Maybe you have it form a plugin? Or you have an WordPress hosted service via wordpress.com?

**Comment by AurelTristen** [comment]
Hello,
I'm an idiot. The reason why I'm seeing this and you are not is because I have Jetpack installed (for added security features). It has an option to shut WP login off.  Sorry about that, and thanks for the quick response!

For anyone else reading this, it's in Jetpack>Settings and then the Security tab.
