### ISSUE TITLE
WPforms not showing up for user

### ISSUE THREAD

**Issue by ronsieb** [bueltge/adminimize#89]
I'm having trouble getting a popular plugin called "WPforms" to work with Adminimize... I've unchecked any boxes related to WPforms in the settings for my Editor, but it has the following problems:

1. WPforms doesn't show up in the left menu bar for the user.
2. There IS a button for "Add Form" in the Blog section, but when the user tries to create a form, it says they don't have access.

Can anyone please help with this? I'm really not sure what to do at this point! Am I missing something simple?

**Comment by bueltge** [comment]
for 1. That's a problem on the plugin. Each plugin that implement a menu item check for an capability, there is inside the role. Adminimize can't change this, its hide only. You can ask the author of the plugin or you give the user and his role the capability there is necessary for access of the menu page, as example you can use the plugin Members to do this.

for 2. I think is the same problem as 1.
