### ISSUE TITLE
Can't manage capabilities as I wish

### ISSUE THREAD

**Issue by SamuelBzn** [bueltge/adminimize#93]
Good evening,

I have a problem with the plugin. I can not manage the permissions as I wish. Indeed, red squares appear in the table, and whether they are checked or not, no change is made.
I tried to create a new role with "Ultimate member", but the problem persists.

Could you help me please ?

Thank you in advance.
Samuel Bazniar

Wordpress Version : 4.9.* (from 1 to 5)
Adminimize : 1.11.4

Screenshot :  https://www.noelshack.com/2018-18-1-1525107740-sans-titre.jpeg

**Comment by bueltge** [comment]
The plugin don't check the capabilities, it read only the user roles. The red bordered checkboxes are only Parent items of the menu, not more.
